crawler/config/routes.rb
Rails.application.routes.draw do
  resources :buscas
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

crawler/app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

crawler/app/models/busca.rb
class Busca < ApplicationRecord
end

crawler/app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

crawler/app/controllers/buscas_controller.rb
class BuscasController < ApplicationController
  before_action :set_busca, only: [:show, :edit, :update, :destroy]

  # GET /buscas
  # GET /buscas.json
  def index
    @buscas = Busca.all
  end

  # GET /buscas/1
  # GET /buscas/1.json
  def show
  end

  # GET /buscas/new
  def new
    @busca = Busca.new
  end

  # GET /buscas/1/edit
  def edit
  end

  # POST /buscas
  # POST /buscas.json
  def create
    @busca = Busca.new(busca_params)

    respond_to do |format|
      if @busca.save
        format.html { redirect_to @busca, notice: 'Busca was successfully created.' }
        format.json { render :show, status: :created, location: @busca }
      else
        format.html { render :new }
        format.json { render json: @busca.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /buscas/1
  # PATCH/PUT /buscas/1.json
  def update
    respond_to do |format|
      if @busca.update(busca_params)
        format.html { redirect_to @busca, notice: 'Busca was successfully updated.' }
        format.json { render :show, status: :ok, location: @busca }
      else
        format.html { render :edit }
        format.json { render json: @busca.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /buscas/1
  # DELETE /buscas/1.json
  def destroy
    @busca.destroy
    respond_to do |format|
      format.html { redirect_to buscas_url, notice: 'Busca was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_busca
      @busca = Busca.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def busca_params
      params.require(:busca).permit(:titulo, :conteudo, :imagem, :link_origem)
    end
end

crawler/app/helpers/application_helper.rb
module ApplicationHelper
end

crawler/app/helpers/buscas_helper.rb
module BuscasHelper
end

crawler/app/views/buscas/_form.html.erb
<%= form_with(model: busca, local: true) do |form| %>
  <% if busca.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(busca.errors.count, "error") %> prohibited this busca from being saved:</h2>

      <ul>
      <% busca.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :titulo %>
    <%= form.text_field :titulo %>
  </div>

  <div class="field">
    <%= form.label :conteudo %>
    <%= form.text_area :conteudo %>
  </div>

  <div class="field">
    <%= form.label :imagem %>
    <%= form.text_field :imagem %>
  </div>

  <div class="field">
    <%= form.label :link_origem %>
    <%= form.text_field :link_origem %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

crawler/app/views/buscas/edit.html.erb
<h1>Editing Busca</h1>

<%= render 'form', busca: @busca %>

<%= link_to 'Show', @busca %> |
<%= link_to 'Back', buscas_path %>

crawler/app/views/buscas/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Buscas</h1>

<table>
  <thead>
    <tr>
      <th>Titulo</th>
      <th>Conteudo</th>
      <th>Imagem</th>
      <th>Link origem</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @buscas.each do |busca| %>
      <tr>
        <td><%= busca.titulo %></td>
        <td><%= busca.conteudo %></td>
        <td><%= busca.imagem %></td>
        <td><%= busca.link_origem %></td>
        <td><%= link_to 'Show', busca %></td>
        <td><%= link_to 'Edit', edit_busca_path(busca) %></td>
        <td><%= link_to 'Destroy', busca, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Busca', new_busca_path %>

crawler/app/views/buscas/new.html.erb
<h1>New Busca</h1>

<%= render 'form', busca: @busca %>

<%= link_to 'Back', buscas_path %>

crawler/app/views/buscas/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Titulo:</strong>
  <%= @busca.titulo %>
</p>

<p>
  <strong>Conteudo:</strong>
  <%= @busca.conteudo %>
</p>

<p>
  <strong>Imagem:</strong>
  <%= @busca.imagem %>
</p>

<p>
  <strong>Link origem:</strong>
  <%= @busca.link_origem %>
</p>

<%= link_to 'Edit', edit_busca_path(@busca) %> |
<%= link_to 'Back', buscas_path %>

crawler/app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Crawler</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>